spring:
  application:
    name: cource-program
  datasource:
    username: root
    password: f944480199@
    url: jdbc:mysql://localhost:3306/paper_program?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  base-packages: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.fengjie.courseprogram.model
mapper:
  not-empty: false
  identity: mysql

