spring:
  application:
    name: cource-program
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/course_program?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  devtools:
    restart:
      enabled: true
      additional-exclude: scr/main/java
      exclude: templates

mybatis:
  type-aliases-package: com.fengjie.courseprogram.model
  mapper-locations: classpath:mybatis/mappers/*.xml
mapper:
  not-empty: false
  identity: mysql
pagehelper:
  helper-dialect: mysql
  params: countSql
  reasonable: false
  support-methods-arguments: true
#logging:
#  level:
#    root: error
#    org:
#      springframework:
#        security: DEBUG
#        web: ERROR
#      hibernate: DEBUG
#      apache:
#        commons:
#          dbcp2: DEBUG
